server:
    min-players: 2

chat:
    chat-format: '<prefix><username>&7: &f<message>'
    prefixes:
        user: '&2'
        vip: '&6'
        staff: '&4'

messages:
    player-join: '<prefix><username> &ehas joined the game!'
    player-quit: '<prefix><username> &ehas left the game!'

motds:
    lobby: '&7Current State: &a&lLobby'
    ingame: '&7Current State: &9&lIn-Game'
    endgame: '&7Current State: &8&lPost-Victory'

times:
    lobby: 60
    ingame: 240
    endgame: 30

block-break-whitelist:
    - 18
    - 39
    - 40
    - 103
    - 106
    - 111