name: CookieSlap
description: A Reloaded version of CookieSlap!
authors: [Xquiset]
version: 0.0.1a
main: rageteam.cookieslap.main.CookieSlap
softdepend: [WorldEdit]
commands:
   toggleboard:
      description: This Will Turn The Scoreboard ON/OFF
      alias: [tb]
      permission: cookieslap.toggleboard