name: CookieSlap
description: A Reloaded version of CookieSlap!
authors: [Xquiset, Rage_Master14, TheMinecraftDomain]
version: 0.0.1a
main: rageteam.cookieslap.main.CS
softdepend: [WorldEdit]
commands: