name: CookieSlap
version: 1.0
main: RageTeam.cookieslap.main.CookieMain
authors: [Rage_Master14,Xquiset,TheMinersDomain]
description: Fully Automated CookieSlap Plugin!

commands:
    CookieSlap:
        description: CookieSlap Command
        usage: /cs <command> <args>
        aliases: [cs, CookieSlap]